language: ruby
addons:
  apt:
    packages:
    # required to avoid SSL errors
    - libcurl4-openssl-dev
cache:
  bundler: true
  directories:
  - _cache/
  - $TRAVIS_BUILD_DIR/tmp/.htmlproofer
rvm:
- 2.4.1

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script: ./_script/cibuild

# branch whitelist, only for GitHub Pages
branches:
  except:
  # gh-pages is automatically committed
  - gh-pages

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
  - GH_REF: github.com/hackercouch/hackercouch.git
