language: ruby
sudo: required
before_install:
  - sudo update-ca-certificates
cache:
  bundler: true
  directories:
  - _cache/
rvm:
- 2.3.0

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script: ./_script/cibuild

# branch whitelist, only for GitHub Pages
branches:
  except:
  # gh-pages is automatically committed
  - gh-pages

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
  - GH_REF: github.com/hackercouch/hackercouch.git
