title: Hackercouch
description: Hospitality for Hackers, by Hackers.
url: https://hackercouch.com

markdown: kramdown
kramdown:
  input: GFM

exclude:
  - .editorconfig
  - .gitignore
  - .travis.yml
  - CNAME
  - Gemfile*
  - Rakefile
  - README.md
  - vendor

collections:
  couches:
    output: true
  # The json collection is a symlink
  # to the _couches collection
  json:
    output: true
    permalink: /couches/:path.json
defaults:
  - scope:
      type: couches
    values:
      layout: couch
  - scope:
      type: json
    values:
      layout: json
