title: Hackercouch
description: Hospitality for Hackers, by Hackers.
url: https://hackercouch.com

markdown: kramdown
kramdown:
  input: GFM

exclude:
  - .editorconfig
  - .gitignore
  - .travis.yml
  - CNAME
  - Gemfile*
  - Rakefile
  - README.md
  - vendor
  - .jekyll-cache

collections:
  couches:
    output: true
  # The json collection is a symlink
  # to the _couches collection
  json:
    output: true
api:
  fields:
    - city
    - country
    - region
    - email
    - github
    - couchsurfing
    - relative_path
    - url
    - content
emptyHash: {}
defaults:
  - scope:
      type: couches
    values:
      layout: couch
  - scope:
      type: json
    values:
      layout: json
      permalink: /couches/:path.json
